import { Pacifico } from "next/font/google";
import "./globals.css";

const inter = Pacifico({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "North Pizza",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
